name: Test Algorithms

on:
  pull_request:
    paths:
      - "algorithms/**"
  push:
    branches: [main]
    paths:
      - "algorithms/**"

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install
      - run: npx vitest run
